// DO NOT CHANGE THESE VALUES - THEY ARE USED TO BUILD ACTIVITIES.
// IF YOU ABSOLUTELY HAVE TO CHANGE, UPDATE ALL ACTIVIES WITH NEW TYPE.
// DIDN'T PUT IN DB CUZ CANT MAKE RELATIONAL JOIN IN NOSQL WITHOUT PERFORMANCE HIT

export default {
    PROFILE_VIEW: 'PROFILE_VIEW',
    PROSPECT_VIEW: 'PROSPECT_VIEW',
    PROSPECT_CREATED: 'PROSPECT_CREATED',
    PROSPECT_DELETED: 'PROSPECT_DELETED',
    RECOMMENDATION: 'RECOMMENDATION',
    MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
    EMPLOYMENT_CHANGE: 'EMPLOYMENT_CHANGE',
    PROFILE_CHANGE: 'PROFILE_CHANGE'
}